# Generated by Django 4.0.4 on 2022-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_yazar_soyadı'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dergiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dergi')),
            ],
        ),
        migrations.CreateModel(
            name='KullanıcıMesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=50)),
                ('soyisim', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=50)),
                ('dosya', models.CharField(max_length=50)),
            ],
        ),
    ]
