# Generated by Django 4.0.4 on 2022-05-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0003_dergiler_kullanıcımesaj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazar',
            old_name='soyadı',
            new_name='unvan',
        ),
        migrations.AlterField(
            model_name='yazar',
            name='image',
            field=models.ImageField(upload_to='yazar'),
        ),
    ]
