# Generated by Django 4.0.4 on 2022-05-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0005_yazar_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanıcımesaj',
            name='dosya',
            field=models.FileField(upload_to='kullanici'),
        ),
    ]
