# Generated by Django 4.0.4 on 2022-05-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0007_dergiler_aciklama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dergiler',
            name='aciklama',
        ),
    ]
