# Generated by Django 4.0.4 on 2022-05-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0008_remove_dergiler_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sayfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
