# Generated by Django 4.0.4 on 2022-05-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0009_sayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dergi')),
                ('aciklama', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Sayfa',
        ),
    ]
