# Generated by Django 4.0.4 on 2022-05-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0010_drgi_delete_sayfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dergisayi',
            name='description',
            field=models.FileField(upload_to='dosya'),
        ),
    ]
