# Generated by Django 4.0.4 on 2022-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0011_alter_dergisayi_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drgi',
            name='aciklama',
            field=models.FileField(upload_to='dosya2'),
        ),
    ]
