# Generated by Django 4.0.4 on 2022-06-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0012_alter_drgi_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drgi',
            name='aciklama',
            field=models.FileField(upload_to='dosya2/'),
        ),
    ]
