# Generated by Django 4.0.4 on 2022-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0013_alter_drgi_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='drgi',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
