# Generated by Django 4.0.4 on 2022-06-02 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0014_drgi_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drgi',
            old_name='title',
            new_name='baslik',
        ),
    ]
