# Generated by Django 4.0.4 on 2022-06-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0015_rename_title_drgi_baslik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dergi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapak', models.ImageField(upload_to='dergi')),
                ('içerik', models.FileField(upload_to='dosya2/')),
                ('baslik', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Dergiler',
        ),
        migrations.DeleteModel(
            name='DergiSayi',
        ),
        migrations.DeleteModel(
            name='Drgi',
        ),
    ]
