# Generated by Django 4.0.4 on 2022-06-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0016_dergi_delete_dergiler_delete_dergisayi_delete_drgi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dergi',
            old_name='içerik',
            new_name='icerik',
        ),
    ]
