# Generated by Django 4.0.4 on 2022-06-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0017_rename_içerik_dergi_icerik'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KullanıcıMesaj',
            new_name='KullaniciMesaj',
        ),
    ]
