# Generated by Django 4.0.4 on 2022-06-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0018_rename_kullanıcımesaj_kullanicimesaj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kullanicimesaj',
            name='dosya',
        ),
    ]
