# Generated by Django 4.0.4 on 2022-06-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0019_remove_kullanicimesaj_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicimesaj',
            name='yazi',
            field=models.CharField(default='', max_length=100),
        ),
    ]
